
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Include:
    - 'exploits/{**/,}*.rb'
  Exclude:
    - 'vendor/**/*'

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# community-pocs specific exceptions
#
Layout/LeadingCommentSpace:
  Exclude:
    - 'Gemfile'
Layout/CommentIndentation:
  Exclude:
    - 'Gemfile'
Naming/FileName:
  Exclude:
    - 'spec/exploits/*/CVE-*_spec.rb'
    - 'spec/exploits/*/GHSA-*_spec.rb'
Naming/ClassAndModuleCamelCase: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/SignalException: { Enabled: false }
Layout/FirstHashElementIndentation: { Enabled: false }
Layout/SpaceAroundOperators: { Enabled: false }
